# Generated by Django 4.0.3 on 2023-05-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user1',
        ),
    ]
