# Generated by Django 4.0.3 on 2023-05-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0007_rename_user_userprofile_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
